apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ko961jppp-go 
  janus-idp.io/tekton: ko961jppp-go
  backstage.io/kubernetes-id: ko961jppp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ko961jppp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  